services:
  # O nosso Gateway (antigo orion-health-hub)
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      target: gateway-final # Diz para usar o estágio 'gateway-final' do Dockerfile
    ports:
      - "1080:1080"
    volumes:
      - ./certs/orionhealth.pfx:/app/certs/orionhealth.pfx:ro
    depends_on:
      - oracle-db
      - rabbitmq
    environment:
      - ConnectionStrings__OracleConnection=User Id=orionhealth;Password=oracle;Data Source=oracle-db:1521/XEPDB1
      - MessageBroker__HostName=rabbitmq
      - Mllp__CertificatePath=/app/certs/orionhealth.pfx

  # O nosso novo Processador de HL7
  hl7-processor:
    build:
      context: .
      dockerfile: Dockerfile
      target: processor-final # Diz para usar o estágio 'processor-final' do Dockerfile
    depends_on:
      - oracle-db
      - rabbitmq
    environment:
      - ConnectionStrings__OracleConnection=User Id=orionhealth;Password=oracle;Data Source=oracle-db:1521/XEPDB1
      - MessageBroker__HostName=rabbitmq

  oracle-db:
    image: gvenzl/oracle-xe:latest
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=oracle
      - APP_USER=orionhealth
      - APP_USER_PASSWORD=oracle
    volumes:
      - oracle_data:/opt/oracle/oradata

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

volumes:
  oracle_data:
